theme: jekyll-theme-dinky
title: david torosyan
github:
  is_project_page: false
  is_user_page: true
hide_description: true
sass:
  sass_dir: assets/css
profile: assets/img/profile.jpg
hide_footer: true
linkedin:
  url: https://www.linkedin.com/in/davidtorosyan/